# ===============================================================
# CONFIGURAÇÕES DO BANCO DE DADOS (MYSQL)
# ===============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/workflow_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Corinthians2021@

# ===============================================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================================================
# O 'update' cria ou atualiza as tabelas automaticamente com base nas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================================================
# CONFIGURAÇÕES DO THYMELEAF (INTERFÁCIA GRÁFICA)
# ===============================================================
# Desativa o cache para que as mudanças no HTML apareçam sem precisar reiniciar o sistema
spring.thymeleaf.cache=false